% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Apr-2023 00:01:09
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------
                                            

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [10.000000000000009 97.999999999999986 0];
smiData.RigidTransform(1).angle = 3.1415926535897931;
smiData.RigidTransform(1).axis = [1 0 0];
smiData.RigidTransform(1).ID = 'B[FrontSegment-1:-:EndEffector-1]';
smiData.RigidTransform(1).ID = convertCharsToStrings( ...
  smiData.RigidTransform(1).ID);
smiData.RigidTransform(2).translation = ...
  [-2.4868995751603507E-13 1.1368683772161603E-12 4.9999999999999929];
smiData.RigidTransform(2).angle = 3.1415926535897931;
smiData.RigidTransform(2).axis = [1 0 0];
smiData.RigidTransform(2).ID = 'F[FrontSegment-1:-:EndEffector-1]';
smiData.RigidTransform(2).ID = convertCharsToStrings( ...
  smiData.RigidTransform(2).ID);
smiData.RigidTransform(3).translation = ...
  [10.000000000000009 26.999999999999996 -36.000000000000007];
smiData.RigidTransform(3).angle = 3.1415926535897931;
smiData.RigidTransform(3).axis = [1 0 0];
smiData.RigidTransform(3).ID = 'B[BackSegment-1:-:FrontSegment-1]';
smiData.RigidTransform(3).ID = convertCharsToStrings( ...
  smiData.RigidTransform(3).ID);
smiData.RigidTransform(4).translation = ...
  [9.99999999999884 22.000000000001272 1];
smiData.RigidTransform(4).angle = 3.1415926535897931;
smiData.RigidTransform(4).axis = [1 0 0];
smiData.RigidTransform(4).ID = 'F[BackSegment-1:-:FrontSegment-1]';
smiData.RigidTransform(4).ID = convertCharsToStrings( ...
  smiData.RigidTransform(4).ID);
smiData.RigidTransform(5).translation = ...
  [0 0 54.999999999999993];
smiData.RigidTransform(5).angle = 0;
smiData.RigidTransform(5).axis = [0 0 0];
smiData.RigidTransform(5).ID = 'B[Base-1:-:BackSegment-1]';
smiData.RigidTransform(5).ID = convertCharsToStrings( ...
  smiData.RigidTransform(5).ID);
smiData.RigidTransform(6).translation = ...
  [9.9999999999993889 117.00000000000165 3];
smiData.RigidTransform(6).angle = 0;
smiData.RigidTransform(6).axis = [0 0 0];
smiData.RigidTransform(6).ID = 'F[Base-1:-:BackSegment-1]';
smiData.RigidTransform(6).ID = convertCharsToStrings( ...
  smiData.RigidTransform(6).ID);
smiData.RigidTransform(7).translation = ...
  [-58.685724127516245 -18.046444276675278 52.499999999999993];
smiData.RigidTransform(7).angle = 0;
smiData.RigidTransform(7).axis = [0 0 0];
smiData.RigidTransform(7).ID = 'RootGround[Base-1]';
smiData.RigidTransform(7).ID = convertCharsToStrings( ...
  smiData.RigidTransform(7).ID);
smiData.Solid = struct;
smiData.Solid(1).mass = 0.0079645464699805782;
smiData.Solid(1).CoM = [9.9999999999999982 51.048735024903969 1.9927520336246018 ...
                        ];
smiData.Solid(1).MoI = [6.8918818829375308 0.26763721829931125 7.1382041784335186 ...
                        ];
smiData.Solid(1).PoI = [-0.0016768895006120394 0 0];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'FrontSegment*:*Standard';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);
smiData.Solid(2).mass = 0.019841938040025903;
smiData.Solid(2).CoM = [10.000000000000004 48.531020882962807 -4.9698979062719344 ...
                        ];
smiData.Solid(2).MoI = [30.532166010937708 2.489353677719242 29.01760053704696 ...
                        ];
smiData.Solid(2).PoI = [-3.5012555532748544 0 0];
smiData.Solid(2).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'BackSegment*:*Standard';
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);
smiData.Solid(3).mass = 0.00019242255003237483;
smiData.Solid(3).CoM = [0 0 2.5000000000000004];
smiData.Solid(3).MoI = [0.00099017437204159536 0.00099017437204159536 0.0011785881189482958 ...
                        ];
smiData.Solid(3).PoI = [0 0 0];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'EndEffector*:*Standard';
smiData.Solid(3).ID = convertCharsToStrings(smiData.Solid(3).ID);
smiData.Solid(4).mass = 0.039743584553019989;
smiData.Solid(4).CoM = [0 2.6802816403712004 11.398117631260853];
smiData.Solid(4).MoI = [17.480530046002848 15.173822367461753 19.086624088287358 ...
                        ];
smiData.Solid(4).PoI = [-0.97986491744756843 0 0];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Base*:*Standard';
smiData.Solid(4).ID = convertCharsToStrings(smiData.Solid(4).ID);
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -163.51262539572758;
smiData.RevoluteJoint(1).ID = '[FrontSegment-1:-:EndEffector-1]';
smiData.RevoluteJoint(1).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(1).ID);
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 168.74823060934443;
smiData.RevoluteJoint(2).ID = '[BackSegment-1:-:FrontSegment-1]';
smiData.RevoluteJoint(2).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(2).ID);
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 5.2356052136168545;
smiData.RevoluteJoint(3).ID = '[Base-1:-:BackSegment-1]';
smiData.RevoluteJoint(3).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(3).ID);

